---
name: Graphics-HotMap
version: 0.0001
author:
  - 'Mathieu Alorent <cpan@kumy.net>'
abstract: Generate thermographic images.
license: gpl3
resources:
  license: http://opensource.org/licenses/gpl-3.0.html
requires:
  Data::Dumper: 0
  File::Temp: 0
  Image::Magick: 0
  Math::Gradient: 0
  PDL: 0
  PDL::IO::Pic: 0
  PDL::NiceSlice: 0
configure_requires:
  Module::Build: 0.340201
provides:
  Graphics::HotMap:
    file: lib/Graphics/HotMap.pm
    version: 0.0001
generated_by: Module::Build version 0.340201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
